// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSquallAssetsGenerator_custom.h file.

#ifndef STUB_SERVER_SQUALLASSETSGENERATOR_H
#define STUB_SERVER_SQUALLASSETSGENERATOR_H

#include "server/SquallAssetsGenerator.h"
#include "stubSquallAssetsGenerator_custom.h"

#ifndef STUB_SquallAssetsGenerator_SquallAssetsGenerator
//#define STUB_SquallAssetsGenerator_SquallAssetsGenerator
   SquallAssetsGenerator::SquallAssetsGenerator(Squall::Repository repository, std::filesystem::path assetsPath)
  {
    
  }
#endif //STUB_SquallAssetsGenerator_SquallAssetsGenerator

#ifndef STUB_SquallAssetsGenerator_generateFromAssets
//#define STUB_SquallAssetsGenerator_generateFromAssets
  std::optional<Squall::Signature> SquallAssetsGenerator::generateFromAssets(const std::string& rootName)
  {
    return *static_cast<std::optional<Squall::Signature>*>(nullptr);
  }
#endif //STUB_SquallAssetsGenerator_generateFromAssets


#endif