
# Standard defines:
CC		=	g++
AR		=	ar
RANLIB		=	ranlib
STDLIBS		=	-L$(OUTDIR)
STDINCS		=	-I.
C_FLAGS		=	-g -D_ADebug_ -Wall

OUTDIR          =	win32
EXE_EXT         =	.exe
incDirs         =	-Ic:/mingw32/include/Python $(STDINCS)
libDirs         =	$(STDLIBS)
LIBS            =	-lAtlas -lpython15 -lwsock32 -lstdc++

include Makefile.common
