#ifndef ERIS_PERL_CONVERSION_H
#define ERIS_PERL_CONVERSION_H

#include <sigcperl/convert.h>

extern "C" {
#include "EXTERN.h"
#include "perl.h"
}
#undef convert
#undef list
#undef ref
#undef scalar

#include "roomhandle.h"
#include "typeinfohandle.h"
#include "refcount.h"
#include "atlas_convert.h"
#include "perlentity.h"

#include <Eris/Person.h>

using Eris::Room;
using Eris::Person;
using Eris::Entity;
// The following autogenerated header file is not complete, and should
// only be included here
#include "conversion_wrapper.h"

#endif // ERIS_PERL_CONVERSION_H
