AtlasObject.o: AtlasObject.cpp AtlasObject.h AtlasDebug.h
AtlasCodec.o: AtlasCodec.cpp AtlasCodec.h AtlasDebug.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h
AtlasClient.o: AtlasClient.cpp AtlasClient.h AtlasCodec.h AtlasDebug.h \
 AtlasObject.h AtlasProtocol.h AtlasProtocolEncoder.h \
 AtlasProtocolDecoder.h AtlasSocket.h
AtlasCodec.o: AtlasCodec.cpp AtlasCodec.h AtlasDebug.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h
AtlasDebug.o: AtlasDebug.cpp AtlasDebug.h
AtlasObject.o: AtlasObject.cpp AtlasObject.h AtlasDebug.h
AtlasPackedAsciiDecoder.o: AtlasPackedAsciiDecoder.cpp AtlasObject.h \
 AtlasDebug.h AtlasProtocol.h AtlasProtocolEncoder.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiDecoder.h
AtlasPackedAsciiEncoder.o: AtlasPackedAsciiEncoder.cpp \
 AtlasPackedAsciiEncoder.h AtlasObject.h AtlasDebug.h \
 AtlasProtocolEncoder.h
AtlasPackedAsciiProtocol.o: AtlasPackedAsciiProtocol.cpp \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasObject.h AtlasDebug.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiProtocol.h \
 AtlasPackedAsciiEncoder.h AtlasPackedAsciiDecoder.h
AtlasProtocol.o: AtlasProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasDebug.h \
 AtlasProtocolDecoder.h
AtlasProtocolDecoder.o: AtlasProtocolDecoder.cpp \
 AtlasProtocolDecoder.h AtlasObject.h AtlasDebug.h
AtlasProtocolEncoder.o: AtlasProtocolEncoder.cpp \
 AtlasProtocolEncoder.h AtlasObject.h AtlasDebug.h
AtlasServer.o: AtlasServer.cpp AtlasServer.h AtlasSocket.h \
 AtlasClient.h AtlasCodec.h AtlasDebug.h AtlasObject.h AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasProtocolDecoder.h
AtlasSocket.o: AtlasSocket.cpp AtlasSocket.h
AtlasTCPSocket.o: AtlasTCPSocket.cpp AtlasTCPSocket.h AtlasSocket.h
AtlasXMLDecoder.o: AtlasXMLDecoder.cpp AtlasObject.h AtlasDebug.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h \
 AtlasXMLDecoder.h
AtlasXMLEncoder.o: AtlasXMLEncoder.cpp AtlasXMLEncoder.h AtlasObject.h \
 AtlasDebug.h AtlasProtocolEncoder.h
AtlasXMLProtocol.o: AtlasXMLProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasDebug.h \
 AtlasProtocolDecoder.h AtlasXMLProtocol.h AtlasXMLEncoder.h \
 AtlasXMLDecoder.h
AtlasCompressor.o: AtlasCompressor.cpp AtlasCompressor.h
ChatClient.o: ChatClient.cpp ChatClient.h
ChatServer.o: ChatServer.cpp SocketTest.h AtlasSocket.h \
 AtlasTCPSocket.h
CodecBench.o: CodecBench.cpp AtlasCodec.h AtlasDebug.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h \
 AtlasXMLProtocol.h AtlasXMLEncoder.h AtlasXMLDecoder.h \
 AtlasPackedAsciiProtocol.h AtlasPackedAsciiEncoder.h \
 AtlasPackedAsciiDecoder.h CodecBench.h
PackedAsciiTest.o: PackedAsciiTest.cpp AtlasCodec.h AtlasDebug.h \
 AtlasObject.h AtlasProtocol.h AtlasProtocolEncoder.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiProtocol.h \
 AtlasPackedAsciiEncoder.h AtlasPackedAsciiDecoder.h PackedAsciiTest.h
SocketTest.o: SocketTest.cpp SocketTest.h AtlasSocket.h \
 AtlasTCPSocket.h
XMLTest.o: XMLTest.cpp XMLTest.h AtlasObject.h AtlasDebug.h \
 AtlasCodec.h AtlasProtocol.h AtlasProtocolEncoder.h \
 AtlasProtocolDecoder.h AtlasXMLProtocol.h AtlasXMLEncoder.h \
 AtlasXMLDecoder.h
