#=======================================================================
#@V@:Note: File automatically generated by VIDE makefile maker (00:55:30 10 Dec 1999) (g++).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC     	=	g++

HOMEV	=	C:/v
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
Src	=	.
libDirs	=
incDirs	=
LIBS	=	-lstdc++ -lpython15
C_FLAGS	=	-g

SRCS	=\
	$(Src)/AtlasCodec.cpp\
	$(Src)/AtlasProtocol.cpp\
	$(Src)/AtlasProtocolDecoder.cpp\
	$(Src)/AtlasProtocolEncoder.cpp\
	$(Src)/AtlasObject.cpp\
	$(Src)/XMLTest.cpp\
	$(Src)/AtlasXMLDecoder.cpp\
	$(Src)/AtlasXMLEncoder.cpp\
	$(Src)/AtlasXMLProtocol.cpp

EXOBJS	=\
	$(oDir)/AtlasCodec.o\
	$(oDir)/AtlasProtocol.o\
	$(oDir)/AtlasProtocolDecoder.o\
	$(oDir)/AtlasProtocolEncoder.o\
	$(oDir)/AtlasObject.o\
	$(oDir)/XMLTest.o\
	$(oDir)/AtlasXMLDecoder.o\
	$(oDir)/AtlasXMLEncoder.o\
	$(oDir)/AtlasXMLProtocol.o

# User defines:

#@# Targets follow ---------------------------------

all:	$(Bin)/XMLTest.exe

objs:	$(EXOBJS)

cleanobjs:
	rm -f $(EXOBJS)

cleanbin:
	rm -f $(Bin)/XMLTest.exe

clean:	 cleanobjs

cleanall:	 cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/XMLTest.exe: $(EXOBJS)
	$(CC) -o $(Bin)/XMLTest.exe $(EXOBJS) $(incDirs) $(libDirs) $(LIBS)

$(oDir)/AtlasCodec.o: AtlasCodec.cpp AtlasCodec.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocol.o: AtlasProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolDecoder.o: AtlasProtocolDecoder.cpp \
 AtlasProtocolDecoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolEncoder.o: AtlasProtocolEncoder.cpp \
 AtlasProtocolEncoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasObject.o: AtlasObject.cpp AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/XMLTest.o: XMLTest.cpp AtlasCodec.h AtlasObject.h AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasProtocolDecoder.h AtlasXMLProtocol.h \
 AtlasXMLEncoder.h AtlasXMLDecoder.h XMLTest.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasXMLDecoder.o: AtlasXMLDecoder.cpp AtlasObject.h AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasProtocolDecoder.h AtlasXMLDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasXMLEncoder.o: AtlasXMLEncoder.cpp AtlasXMLEncoder.h AtlasObject.h \
 AtlasProtocolEncoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasXMLProtocol.o: AtlasXMLProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasProtocolDecoder.h \
 AtlasXMLProtocol.h AtlasXMLEncoder.h AtlasXMLDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
