#=======================================================================
#@V@:Note: File automatically generated by VIDE makefile maker (22:26:44 10 Dec 1999) (g++).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC     	=	g++

HOMEV	=	C:/v
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
Src	=	.
libDirs	=
incDirs	=
LIBS	=	-lstdc++ -lpython15
C_FLAGS	=	-g -D_ADebug_

SRCS	=\
	$(Src)/AtlasCodec.cpp\
	$(Src)/AtlasPackedAsciiDecoder.cpp\
	$(Src)/AtlasPackedAsciiEncoder.cpp\
	$(Src)/AtlasPackedAsciiProtocol.cpp\
	$(Src)/AtlasProtocol.cpp\
	$(Src)/AtlasProtocolDecoder.cpp\
	$(Src)/AtlasProtocolEncoder.cpp\
	$(Src)/AtlasSocket.cpp\
	$(Src)/PackedAsciiTest.cpp\
	$(Src)/AtlasObject.cpp\
	$(Src)/AtlasDebug.cpp

EXOBJS	=\
	$(oDir)/AtlasCodec.o\
	$(oDir)/AtlasPackedAsciiDecoder.o\
	$(oDir)/AtlasPackedAsciiEncoder.o\
	$(oDir)/AtlasPackedAsciiProtocol.o\
	$(oDir)/AtlasProtocol.o\
	$(oDir)/AtlasProtocolDecoder.o\
	$(oDir)/AtlasProtocolEncoder.o\
	$(oDir)/AtlasSocket.o\
	$(oDir)/PackedAsciiTest.o\
	$(oDir)/AtlasObject.o\
	$(oDir)/AtlasDebug.o

# User defines:

#@# Targets follow ---------------------------------

all:	$(Bin)/PackedAsciiTest.exe

objs:	$(EXOBJS)

cleanobjs:
	rm -f $(EXOBJS)

cleanbin:
	rm -f $(Bin)/PackedAsciiTest.exe

clean:	 cleanobjs

cleanall:	 cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/PackedAsciiTest.exe: $(EXOBJS)
	$(CC) -o $(Bin)/PackedAsciiTest.exe $(EXOBJS) $(incDirs) $(libDirs) $(LIBS)

$(oDir)/AtlasCodec.o: AtlasCodec.cpp AtlasCodec.h AtlasDebug.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiDecoder.o: AtlasPackedAsciiDecoder.cpp AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h \
 AtlasPackedAsciiDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiEncoder.o: AtlasPackedAsciiEncoder.cpp \
 AtlasPackedAsciiEncoder.h AtlasObject.h AtlasProtocolEncoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiProtocol.o: AtlasPackedAsciiProtocol.cpp \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasObject.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiProtocol.h \
 AtlasPackedAsciiEncoder.h AtlasPackedAsciiDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocol.o: AtlasProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolDecoder.o: AtlasProtocolDecoder.cpp \
 AtlasProtocolDecoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolEncoder.o: AtlasProtocolEncoder.cpp \
 AtlasProtocolEncoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasSocket.o: AtlasSocket.cpp AtlasSocket.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/PackedAsciiTest.o: PackedAsciiTest.cpp AtlasCodec.h AtlasDebug.h \
 AtlasObject.h AtlasProtocol.h AtlasProtocolEncoder.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiProtocol.h \
 AtlasPackedAsciiEncoder.h AtlasPackedAsciiDecoder.h PackedAsciiTest.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasObject.o: AtlasObject.cpp AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasDebug.o: AtlasDebug.cpp AtlasDebug.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
