#=======================================================================
#@V@:Note: File automatically generated by VIDE makefile maker (06:57:20 07 Dec 1999) (g++).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC     	=	g++

HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
Src	=	.
libDirs	=	-L$(HOMEV)/lib

incDirs	=	-I$(HOMEV)/include

LIBS	=	-lpython15 -lwsock32 -lcomctl32 -mwindows
C_FLAGS	=	-O

SRCS	=\
	$(Src)/AtlasObject.cpp\
	$(Src)/AtlasSocket.cpp\
	$(Src)/AtlasTCPSocket.cpp\
	$(Src)/SocketTest.cpp\
	$(Src)/AtlasClient.cpp\
	$(Src)/AtlasServer.cpp\
	$(Src)/AtlasCodec.cpp\
	$(Src)/AtlasPackedAsciiDecoder.cpp\
	$(Src)/AtlasPackedAsciiEncoder.cpp\
	$(Src)/AtlasPackedAsciiProtocol.cpp\
	$(Src)/AtlasProtocolDecoder.cpp\
	$(Src)/AtlasProtocolEncoder.cpp\
	$(Src)/AtlasProtocol.cpp

EXOBJS	=\
	$(oDir)/AtlasObject.o\
	$(oDir)/AtlasSocket.o\
	$(oDir)/AtlasTCPSocket.o\
	$(oDir)/SocketTest.o\
	$(oDir)/AtlasClient.o\
	$(oDir)/AtlasServer.o\
	$(oDir)/AtlasCodec.o\
	$(oDir)/AtlasPackedAsciiDecoder.o\
	$(oDir)/AtlasPackedAsciiEncoder.o\
	$(oDir)/AtlasPackedAsciiProtocol.o\
	$(oDir)/AtlasProtocolDecoder.o\
	$(oDir)/AtlasProtocolEncoder.o\
	$(oDir)/AtlasProtocol.o

# User defines:

#@# Targets follow ---------------------------------

all:	$(Bin)/SocketTest

objs:	$(EXOBJS)

cleanobjs:
	rm -f $(EXOBJS)

cleanbin:
	rm -f $(Bin)/SocketTest

clean:	 cleanobjs

cleanall:	 cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/SocketTest: $(EXOBJS)
	$(CC) -o $(Bin)/SocketTest $(EXOBJS) $(incDirs) $(libDirs) $(LIBS)

$(oDir)/AtlasObject.o: AtlasObject.cpp AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasSocket.o: AtlasSocket.cpp AtlasSocket.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasTCPSocket.o: AtlasTCPSocket.cpp AtlasTCPSocket.h AtlasSocket.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/SocketTest.o: SocketTest.cpp SocketTest.h AtlasSocket.h \
 AtlasTCPSocket.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasClient.o: AtlasClient.cpp AtlasClient.h AtlasCodec.h \
 AtlasObject.h AtlasProtocol.h AtlasProtocolEncoder.h \
 AtlasProtocolDecoder.h AtlasSocket.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasServer.o: AtlasServer.cpp AtlasServer.h AtlasSocket.h \
 AtlasClient.h AtlasCodec.h AtlasObject.h AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasCodec.o: AtlasCodec.cpp AtlasCodec.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiDecoder.o: AtlasPackedAsciiDecoder.cpp AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h \
 AtlasPackedAsciiDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiEncoder.o: AtlasPackedAsciiEncoder.cpp \
 AtlasPackedAsciiEncoder.h AtlasObject.h AtlasProtocolEncoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiProtocol.o: AtlasPackedAsciiProtocol.cpp \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasObject.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiProtocol.h \
 AtlasPackedAsciiEncoder.h AtlasPackedAsciiDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolDecoder.o: AtlasProtocolDecoder.cpp \
 AtlasProtocolDecoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolEncoder.o: AtlasProtocolEncoder.cpp \
 AtlasProtocolEncoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocol.o: AtlasProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
