# Targets follow ---------------------------------

TARGETS = \
	$(OUTDIR)/CodecBench$(EXE_EXT) \
	$(OUTDIR)/SocketTest$(EXE_EXT) \
	$(OUTDIR)/XMLTest$(EXE_EXT) \
	$(OUTDIR)/PackedAsciiTest$(EXE_EXT) \
	$(OUTDIR)/EchoTest$(EXE_EXT) \
	$(OUTDIR)/CopyTest$(EXE_EXT) \

all:		$(TARGETS)

cleanobjs:
		rm -f $(OUTDIR)/*.o $(OUTDIR)/*.a

cleanbin:
		rm -f $(TARGETS)

clean:	 	cleanobjs

cleanall:	cleanobjs cleanbin

# custom make rules

.cpp.o:
	$(CC) $(C_FLAGS) -c -o $@ $< $(incDirs)

# Target rules follow -----------------------------

$(OUTDIR)/PackedAsciiTest$(EXE_EXT): $(OUTDIR)/PackedAsciiTest.o $(OUTDIR)/libAtlas.a
	$(CCC) -o $(OUTDIR)/PackedAsciiTest$(EXE_EXT) $(OUTDIR)/PackedAsciiTest.o $(incDirs) $(libDirs) $(LIBS)

$(OUTDIR)/XMLTest$(EXE_EXT): $(OUTDIR)/XMLTest.o $(OUTDIR)/libAtlas.a
	$(CCC) -o $(OUTDIR)/XMLTest$(EXE_EXT) $(OUTDIR)/XMLTest.o $(incDirs) $(libDirs) $(LIBS)

$(OUTDIR)/SocketTest$(EXE_EXT): $(OUTDIR)/SocketTest.o $(OUTDIR)/libAtlas.a
	$(CCC) -o $(OUTDIR)/SocketTest$(EXE_EXT) $(OUTDIR)/SocketTest.o $(incDirs) $(libDirs) $(LIBS)

$(OUTDIR)/CodecBench$(EXE_EXT): $(OUTDIR)/CodecBench.o $(OUTDIR)/libAtlas.a
	$(CCC) -o $(OUTDIR)/CodecBench$(EXE_EXT) $(OUTDIR)/CodecBench.o $(incDirs) $(libDirs) $(LIBS)

$(OUTDIR)/EchoTest$(EXE_EXT): $(OUTDIR)/EchoTest.o $(OUTDIR)/libAtlas.a
	$(CCC) -o $(OUTDIR)/EchoTest$(EXE_EXT) $(OUTDIR)/EchoTest.o $(incDirs) $(libDirs) $(LIBS)

$(OUTDIR)/CopyTest$(EXE_EXT): $(OUTDIR)/CopyTest.o $(OUTDIR)/libAtlas.a
	$(CCC) -o $(OUTDIR)/CopyTest$(EXE_EXT) $(OUTDIR)/CopyTest.o $(incDirs) $(libDirs) $(LIBS)

# Dependency rules follow -----------------------------

$(OUTDIR)/CodecBench.o: CodecBench.cpp CodecBench.h
	$(CCC) $(C_FLAGS) -c -o $@ $< $(incDirs)

$(OUTDIR)/PackedAsciiTest.o: PackedAsciiTest.cpp PackedAsciiTest.h
	$(CCC) $(C_FLAGS) -c -o $@ $< $(incDirs)

$(OUTDIR)/SocketTest.o: SocketTest.cpp SocketTest.h 
	$(CCC) $(C_FLAGS) -c -o $@ $< $(incDirs)

$(OUTDIR)/XMLTest.o: XMLTest.cpp XMLTest.h 
	$(CCC) $(C_FLAGS) -c -o $@ $< $(incDirs)

$(OUTDIR)/EchoTest.o: EchoTest.cpp EchoTest.h 
	$(CCC) $(C_FLAGS) -c -o $@ $< $(incDirs)

$(OUTDIR)/CopyTest.o: CopyTest.cpp CopyTest.h 
	$(CCC) $(C_FLAGS) -c -o $@ $< $(incDirs)


